name: CD

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64, arm64, arm]
        include:
          - goos: windows
            goarch: amd64
          - goos: darwin
            goarch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Determine Go version from go.mod
        run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_ENV
      - name: Release
        uses: wangyoucao577/go-release-action@v1.26
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: ${{ env.GO_VERSION }}
          binary_name: "qbittorrent_exporter"
          extra_files: LICENSE README.md
          sha256sum: true
          md5sum: false
